In [1]:
import numpy as np

In [2]:
a = [1, 3, 6, 9, 10]

In [7]:
a

[1, 3, 6, 9, 10]

In [3]:
type(a)

list

In [9]:
np_a = np.array([23, 123, 9])

In [10]:
np_a

array([ 23, 123,   9])

In [11]:
type(np_a)

numpy.ndarray

In [13]:
np_a = np.array([23, 123, 9], dtype='float')

In [14]:
np_a

array([ 23., 123.,   9.])

In [15]:
np_a.shape

(3,)

In [16]:
a = np.random.normal(size=(4, 5)) #random number from normal distribution

In [17]:
a

array([[-0.75669273, -0.52569332,  0.33006363,  1.08272948, -1.69669759],
       [-0.20686602, -0.99807887,  1.81402027, -0.30554483,  0.67364701],
       [-0.13746947, -0.66716072,  0.0442224 ,  1.90738627, -1.73105901],
       [ 0.16663687,  0.65391765,  1.35259215,  0.7380746 ,  0.32690683]])

In [18]:
a.shape

(4, 5)

In [23]:
a = np.random.normal(loc=2, scale=0.1, size=(5, 2, 3))

In [24]:
a

array([[[1.86795764, 1.97848333, 2.07244034],
        [1.87824506, 1.85122838, 2.00144778]],

       [[1.96286548, 1.84002633, 2.01852158],
        [1.97771978, 2.06355454, 2.03997298]],

       [[1.76640436, 2.04802498, 2.09885043],
        [1.98899779, 1.90214127, 2.01252072]],

       [[2.02585467, 1.93097518, 1.92233434],
        [2.32435182, 1.91631719, 2.04431367]],

       [[1.84432181, 1.93031606, 1.80967194],
        [1.92217788, 2.06007119, 2.00419601]]])

In [25]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = np.random.randint(1, 100, size=(3, 3))

In [30]:
b

array([[19, 96, 56],
       [47, 61, 96],
       [16, 14, 31]])

In [31]:
np.ones(shape=(5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.zeros(shape=(3, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.linspace(0, 10, 26)

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,
        4.4,  4.8,  5.2,  5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,
        8.8,  9.2,  9.6, 10. ])

In [37]:
np.logspace(0, 10, 26)

array([1.00000000e+00, 2.51188643e+00, 6.30957344e+00, 1.58489319e+01,
       3.98107171e+01, 1.00000000e+02, 2.51188643e+02, 6.30957344e+02,
       1.58489319e+03, 3.98107171e+03, 1.00000000e+04, 2.51188643e+04,
       6.30957344e+04, 1.58489319e+05, 3.98107171e+05, 1.00000000e+06,
       2.51188643e+06, 6.30957344e+06, 1.58489319e+07, 3.98107171e+07,
       1.00000000e+08, 2.51188643e+08, 6.30957344e+08, 1.58489319e+09,
       3.98107171e+09, 1.00000000e+10])

In [38]:
b = np.linspace(0, 100, 120)

In [39]:
b

array([  0.        ,   0.84033613,   1.68067227,   2.5210084 ,
         3.36134454,   4.20168067,   5.04201681,   5.88235294,
         6.72268908,   7.56302521,   8.40336134,   9.24369748,
        10.08403361,  10.92436975,  11.76470588,  12.60504202,
        13.44537815,  14.28571429,  15.12605042,  15.96638655,
        16.80672269,  17.64705882,  18.48739496,  19.32773109,
        20.16806723,  21.00840336,  21.8487395 ,  22.68907563,
        23.52941176,  24.3697479 ,  25.21008403,  26.05042017,
        26.8907563 ,  27.73109244,  28.57142857,  29.41176471,
        30.25210084,  31.09243697,  31.93277311,  32.77310924,
        33.61344538,  34.45378151,  35.29411765,  36.13445378,
        36.97478992,  37.81512605,  38.65546218,  39.49579832,
        40.33613445,  41.17647059,  42.01680672,  42.85714286,
        43.69747899,  44.53781513,  45.37815126,  46.21848739,
        47.05882353,  47.89915966,  48.7394958 ,  49.57983193,
        50.42016807,  51.2605042 ,  52.10084034,  52.94

In [40]:
b.ndim

1

In [41]:
b.size

120

In [42]:
b.shape

(120,)

In [45]:
a = np.random.normal(0, 1, (4, 8))

In [46]:
a

array([[-0.27342583, -1.4591166 , -0.04635367,  0.16495658, -1.21618884,
        -1.35252525, -0.67305278,  1.03328194],
       [ 0.68713684, -1.04831405, -0.29016914,  1.55501574,  1.08417643,
        -0.21484744,  2.40734023,  0.11454553],
       [ 1.07348205,  2.0692453 ,  0.34640966, -0.51874258, -1.18923939,
        -0.62494684, -2.14732077, -0.74818957],
       [-2.01107835, -0.5238669 ,  0.0490054 , -1.56504006,  2.42649066,
         0.12863411,  1.19020139,  0.70839177]])

In [47]:
a.ndim

2

In [48]:
a.size

32

In [49]:
a.shape

(4, 8)

In [50]:
b = np.arange(24)

In [51]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
b.shape

(24,)

In [53]:
b.reshape((3, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [54]:
b.shape

(24,)

In [55]:
b = b.reshape((3, 8))

In [56]:
b.shape

(3, 8)

In [57]:
a = np.linspace(0, 100, 26)

In [58]:
a

array([  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,
        44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,
        88.,  92.,  96., 100.])

In [59]:
a.shape

(26,)

In [60]:
a = a.reshape((26, 1))

In [61]:
a.shape

(26, 1)

In [62]:
a

array([[  0.],
       [  4.],
       [  8.],
       [ 12.],
       [ 16.],
       [ 20.],
       [ 24.],
       [ 28.],
       [ 32.],
       [ 36.],
       [ 40.],
       [ 44.],
       [ 48.],
       [ 52.],
       [ 56.],
       [ 60.],
       [ 64.],
       [ 68.],
       [ 72.],
       [ 76.],
       [ 80.],
       [ 84.],
       [ 88.],
       [ 92.],
       [ 96.],
       [100.]])

In [63]:
a.reshape((1, 26))

array([[  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,
         44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,
         88.,  92.,  96., 100.]])

In [66]:
c = np.arange(120).reshape((3, 2, 5, 4))

In [68]:
c.shape

(3, 2, 5, 4)

In [72]:
c.reshape((10, 3, 4))

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35]],

       [[ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59]],

       [[ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71]],

       [[ 72,  73,  74,  75],
        [ 76,  77,  78,  79],
        [ 80,  81,  82,  83]],

       [[ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107]],

       [[108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]]])

In [73]:
d = np.arange(720).reshape((3, 2, 5, 4, 6))

In [77]:
d = d.reshape((20, -1))

In [78]:
d.shape

(20, 36)

In [79]:
d = d.reshape((-1, 2, 10))

In [80]:
d.shape

(36, 2, 10)

In [82]:
d.reshape((-1, -1, 10)) #Not Accepted! 

ValueError: can only specify one unknown dimension

In [84]:
d.mean()

359.5

In [85]:
d.sum()

258840

In [90]:
a = np.arange(32).reshape((4, 8))

In [91]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [93]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [94]:
a[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [98]:
a[:,0]

1

In [99]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [100]:
a[:,0:2]

array([[ 0,  1],
       [ 8,  9],
       [16, 17],
       [24, 25]])

In [101]:
a[1:3, 3:6]

array([[11, 12, 13],
       [19, 20, 21]])

In [102]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [103]:
a[[0, 2]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [104]:
b = np.arange(5, 25)

In [105]:
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [108]:
b.shape

(20,)

In [107]:
b[[0, 2, 6, 8, 12, 14, 18]]

array([ 5,  7, 11, 13, 17, 19, 23])

In [109]:
b[np.arange(0, 20, 2)]

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [110]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [111]:
a[2:,[0, 1, 3]]

array([[16, 17, 19],
       [24, 25, 27]])

In [112]:
b = np.arange(21).reshape((3, 7))
c = np.random.normal(size=(3, 7))

In [113]:
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [114]:
c

array([[ 0.34057617,  1.03985879,  0.97438701,  1.16346536, -0.35927425,
        -0.32368346, -0.25680565],
       [ 0.20971646,  1.155872  , -0.7359095 , -0.43751864, -0.16022277,
         0.44923062, -0.0453956 ],
       [-0.59290881, -1.21567193,  0.34844958, -0.63724033, -1.53338921,
        -0.34301148, -1.57949357]])

In [115]:
b.shape, c.shape

((3, 7), (3, 7))

In [116]:
np.concatenate((b, c), axis=0).shape

(6, 7)

In [117]:
np.concatenate((b, c), axis=1).shape

(3, 14)

In [126]:
b = b.reshape((3, 7, 1))
c = c.reshape((3, 7, 1))

In [127]:
c.shape, b.shape

((3, 7, 1), (3, 7, 1))

In [128]:
np.concatenate((b, c), axis=2).shape

(3, 7, 2)

In [130]:
a = np.arange(1, 20)

In [131]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [137]:
def inversing(array):
    nums = []
    for n in array:
        nums.append(1/n)
    return np.array(nums)

In [138]:
inversing(a)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [140]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [145]:
a = np.random.normal(size=(100000))

In [146]:
%timeit inversing(a)

60.2 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [147]:
%timeit 1/a

328 µs ± 2.89 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [148]:
b = np.random.normal(size=(16))

In [149]:
b

array([ 1.81819328, -0.38200457,  1.04126387,  1.40495149, -0.87425532,
       -1.14312789,  0.19505384, -1.03630475,  1.55655126, -0.83770407,
       -0.03954594, -0.44666367,  0.81506443, -0.20282909,  1.44633466,
       -0.02017256])

In [150]:
np.sum(b)

3.2948049762870246

In [151]:
b + 10

array([11.81819328,  9.61799543, 11.04126387, 11.40495149,  9.12574468,
        8.85687211, 10.19505384,  8.96369525, 11.55655126,  9.16229593,
        9.96045406,  9.55333633, 10.81506443,  9.79717091, 11.44633466,
        9.97982744])

In [152]:
np.add(b, 10)

array([11.81819328,  9.61799543, 11.04126387, 11.40495149,  9.12574468,
        8.85687211, 10.19505384,  8.96369525, 11.55655126,  9.16229593,
        9.96045406,  9.55333633, 10.81506443,  9.79717091, 11.44633466,
        9.97982744])

In [153]:
b * 10

array([ 18.18193278,  -3.82004572,  10.41263872,  14.0495149 ,
        -8.74255319, -11.43127891,   1.95053845, -10.36304752,
        15.56551258,  -8.37704069,  -0.39545941,  -4.46663667,
         8.15064433,  -2.0282909 ,  14.46334664,  -0.20172563])

In [154]:
np.sin(a)

array([ 0.98693597,  0.92464449,  0.66873336, ..., -0.99208624,
        0.42232319,  0.08238896])

In [155]:
np.cos(a)

array([0.16111296, 0.38083142, 0.74350232, ..., 0.12555829, 0.90644532,
       0.99660025])

In [156]:
np.exp(a)

array([4.09177183, 3.25470297, 2.08028283, ..., 0.23576829, 1.54651925,
       1.08597962])

In [157]:
np.exp2(a)

array([2.65548998, 2.26592643, 1.66152023, ..., 0.36731615, 1.35285457,
       1.05883842])

In [158]:
np.pi

3.141592653589793

In [159]:
np.e

2.718281828459045

In [163]:
np.mean(a)

0.0021915942426893077

In [166]:
b.shape

(16,)

In [167]:
c = np.random.randint(0, 20, size=(10, 5))

In [168]:
c

array([[12,  3,  1,  3,  8],
       [10,  7, 18, 12,  9],
       [17,  2,  0, 18, 13],
       [10,  4,  8, 15,  9],
       [12,  4, 18, 10, 15],
       [ 3, 15, 17, 17,  7],
       [15,  1,  8,  8, 12],
       [ 1,  7,  5, 12, 13],
       [18, 19,  9, 13, 16],
       [13,  6,  2,  7,  5]])

In [169]:
c.mean(axis=0)

array([11.1,  6.8,  8.6, 11.5, 10.7])

In [171]:
c.sum(axis=0)/10

array([11.1,  6.8,  8.6, 11.5, 10.7])

In [172]:
c.mean(axis=1)

array([ 5.4, 11.2, 10. ,  9.2, 11.8, 11.8,  8.8,  7.6, 15. ,  6.6])

In [177]:
c.prod(axis=0)

array([-1717223296,     8043840,           0,  1550464512, -1846092288])

In [185]:
a = np.random.normal(5, 5, (10))

In [186]:
a

array([13.30383392,  3.53697888, -0.22112232,  8.84919742,  0.56669594,
       16.56952357, 13.21339358, 11.06586372,  3.05797488,  2.01325151])

In [187]:
np.max(a)

16.569523571873617

In [189]:
np.max(a.reshape((2, 5)))

16.569523571873617

In [190]:
np.argmax(a)

5

In [191]:
a[5]

16.569523571873617

In [193]:
a = a.reshape((2, 5))

In [194]:
a

array([[13.30383392,  3.53697888, -0.22112232,  8.84919742,  0.56669594],
       [16.56952357, 13.21339358, 11.06586372,  3.05797488,  2.01325151]])

In [195]:
np.argmax(a)

5

In [197]:
a.reshape((-1,))[5]

16.569523571873617

In [198]:
a.ravel()[5]

16.569523571873617